### ISSUE TITLE
where will be put the keywords ? if we can add keywords.txt line by line that would be good but ı couldnt see in that code

### ISSUE THREAD

**Issue by yasinakay596** [FayzulSaimun/people-also-ask#2]
where will be put the keywords ? if we can add keywords.txt line by line that would be good but ı couldnt see in that code
it would be also perfect if you can add proxy support.

**Comment by FayzulSaimun** [comment]
@yasinakay596 I have added the proxy option and keyword read option from a text file. You can also use csv/excel to read your keywords list.
