### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by yasinakay596** [FayzulSaimun/people-also-ask#3]
i tried this project but it gives so many captchas. i tried with rotation proxies.

**Comment by FayzulSaimun** [comment]
Which proxy providers did you use? Google will throw captcha if you use normal data center proxies. I have used scraperapi and brightdata anf never faced captcha.

**Comment by yasinakay596** [comment]
They are so expensive. i used cheap ones. 1 gb per 15 - 20 dolar too much.
